// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type ErrorResponse = {
    message: string;
    success: false;
};

export type SuccessResponse<T> = {
    message: string;
    success: true;
    data: T;
};

type ApiResponse<T> = ErrorResponse | SuccessResponse<T>;

export type Entity<T> = ApiResponse<T>;

export enum RegulationEnum {
    FCA = "FCA",
}

export type Citation = {
    document_id: string;
    id: number;
    file_url: string;
    quotes: string[];
};

export type RagSearchAnswerData = {
    answer: string;
    citations: Citation[];
    completed: boolean;
};

export type RagSearchAnswer = Entity<RagSearchAnswerData>;
