services:
  finsecured-db:
    image: pgvector/pgvector:pg16
    container_name: finsecured-postgres
    environment:
      POSTGRES_PASSWORD: 20032001Orte
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped

  finsecured-scraper:
    build: ./regulatory_scraper
    container_name: finsecured-scraper
    env_file:
      - ./regulatory_scraper/.env
    depends_on:
      - finsecured-db

  pgadmin:
    image: dpage/pgadmin4
    container_name: finsecured-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: sedorodion@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - finsecured-db
    restart: unless-stopped

volumes:
  data: