services:
  goldenkey-db:
    image: pgvector/pgvector:pg16
    container_name: goldenkey-postgres
    environment:
      POSTGRES_PASSWORD: 20032001Orte
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped

  goldenkey-scraper:
    build: ./regulatory_scraper
    container_name: goldenkey-scraper
    env_file:
      - ./regulatory_scraper/.env
    depends_on:
      - goldenkey-db

  pgadmin:
    image: dpage/pgadmin4
    container_name: goldenkey-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: sedorodion@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - goldenkey-db
    restart: unless-stopped

volumes:
  data: