services:
  finsecured-server:
    build:
      context: ./main-server
      dockerfile: Dockerfile
      args:
        - PORT=4000
        - AI_API_URL=http://finsecured-ai-server:5000
        - NODE_ENV=production
        - CORS_ORIGIN=http://localhost:80 
        - MAIN_DATABASE_URL=${MAIN_DATABASE_URL}
        - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
        - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
        - AUTH0_DOMAIN=${AUTH0_DOMAIN}
        - AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}
        - FINSECURED_API_KEY=${FINSECURED_API_KEY}
    image: sedorodion/finsecured-server:latest
    container_name: "server"
    depends_on:
      - finsecured-postgres
    networks:
      - net

  finsecured-ai-server:
    build:
      context: ./ai-server
      dockerfile: Dockerfile
      args:
        - CORS_ORIGIN=http://finsecured-server:5000
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - COHERE_API_KEY=${COHERE_API_KEY}
        - FINSECURED_API_KEY=${FINSECURED_API_KEY}
        - QDRANT_URL=${QDRANT_URL}
        - PORT=5000
        - WORKERS=1
    image: sedorodion/finsecured-ai-server:latest
    container_name: "ai-server"
    networks:
      - net

  finsecured-client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:80 
    image: sedorodion/finsecured-client:latest
    container_name: "client"
    depends_on:
      - finsecured-server
      - finsecured-ai-server
    networks:
      - net

  reverse-proxy:
    build: ./nginx
    image: sedorodion/reverse-proxy:latest
    container_name: "reverse-proxy"
    restart: always
    depends_on:
      - finsecured-server
      - finsecured-ai-server
      - finsecured-client
    networks:
      - net
    ports:
      - "80:80"
      - "443:443"

  finsecured-postgres:
    image: postgres:16
    container_name: "finsecured-postgres"
    environment:
      - POSTGRES_DB=main_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=20032001Orte
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - net

volumes:
  postgres-data:
    driver: local

networks:
  net:
    driver: bridge